# Custom Language File for Launcher Customizer

[ejs.app]
title = "WAR Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur WAR Country"
welcomeDescription = "Ta mission est de créer ta base secrète en créant ton pays, et qui sait des bombes nucléaires.."
welcomeDescCTA = "Vous n'êtes qu'à quelques clics de WAR Country."
